import type { NextPage } from 'next';
import Head from 'next/head';
import HeroSection from 'modules/home/HeroSection';
import SelectedProjects from 'modules/home/SelectedProjects';
import RecentArticles from 'modules/home/RecentArticles';
import NextPageButton from '@/components/NextPageButton';
import Footer from '@/components/Footer';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bartosz Rajchert Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <div className="space-y-112">
          <SelectedProjects />
          <RecentArticles />
          <NextPageButton />
          <Footer />
        </div>
      </main>
    </>
  );
};

export default Home;
