import type { NextPage } from 'next';
import Head from 'next/head';
import Navigation from '@/components/Navigation';
import Button from '@/components/Button';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Bartosz Rajchert Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <div className="h-screen flex items-center">
          <div className="flex justify-between items-center">
            <div className="lg:w-3/5">
              <h1 className="font-serif text-24 mb-8 lg:text-42">
                Hello! I’m <span className="text-accent">Bartosz Rajchert</span>
              </h1>
              <p className="text-16 mb-12 lg:text-24">
                A Product Designer and Front-End Developer who is delivering
                high quality end-to-end projects.
              </p>
              <p className="text-16 mb-24 lg:text-24">
                Currently working at <b>Accenture Song in Warsaw</b>
              </p>
              <div className="space-x-8">
                <Button text="email" />
                <Button text="linkedin" />
                <Button text="github" />
                <Button text="medium" />
              </div>
            </div>
            <div className="hidden w-1/4 lg:block">
              <img src="/circle.svg" alt="Circle" />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
